hw11_django/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<int:pk>/', views.single_post_page),
    path('', views.index),

]

hw11_django/single_pages/urls.py
from django.urls import path
from . import views

app_name = 'single_pages'

urlpatterns = [
    path("kmpage/", views.km, name="km"),
    path("", views.landing_page, name="landing"),
    path("gyPage/", views.gy, name="gy"),
    path("blog/", views.blog, name="blog"),
    path("todo/", views.todo, name="todo"),
]

hw11_django/softeng2024_prj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("todo/", include("todo_app.urls")),
    path('blog/', include('blog.urls')),
    path("admin/", admin.site.urls),
    path("", include("single_pages.urls"))
]

hw11_django/todo_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ListListView.as_view(), name='index'),
    path("list/<int:list_id>/", views.ItemListView.as_view(), name="list"),
    # CRUD patterns for ToDoLists
    path("list/add/", views.ListCreate.as_view(), name="list-add"),
    path("list/<int:pk>/delete/", views.ListDelete.as_view(), name="list-delete"),
    # CRUD patterns for ToDoItems
    path("list/<int:list_id>/item/add/", views.ItemCreate.as_view(), name="item-add"),
    path("list/<int:list_id>/item/<int:pk>/", views.ItemUpdate.as_view(), name="item-update"),
    path("list/<int:list_id>/item/<int:pk>/delete/", views.ItemDelete.as_view(), name="item-delete"),
]

hw11_django/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'[{self.pk}] {self.title}'

    def get_absolute_url(self):
        return f'/blog/{self.pk}/'

hw11_django/todo_app/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

def one_week_hence():
    return timezone.now() + timezone.timedelta(days=7)

class ToDoList(models.Model):
    title = models.CharField(max_length=100, unique=True)

    def get_absolute_url(self):
        return reverse("list", args=[self.id])

    def __str__(self):
        return self.title

class ToDoItem(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    due_date = models.DateTimeField(default=one_week_hence)
    todo_list = models.ForeignKey(ToDoList, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse(
            "item-update", args=[str(self.todo_list.id), str(self.id)]
        )

    def __str__(self):
        return f"{self.title}: due {self.due_date}"

    class Meta:
        ordering = ["due_date"]

hw11_django/blog/views.py
from django.shortcuts import render
from .models import Post

# Create your views here.
def index(request):
    posts = Post.objects.all().order_by('-pk')

    return render(
        request,
        'blog/index.html',
        {
            'posts': posts,
        }
    )

def single_post_page(request, pk):
    post = Post.objects.get(pk=pk)

    return render(
        request,
        'blog/single_post_page.html',
        {
            'post':post,
        }
    )

hw11_django/single_pages/views.py
from django.shortcuts import render
import pandas as pd

# Create your views here.
def landing_page(request):
    return render(request,'single_pages/landing.html', {'title':'landing'})

def kmpage(request):
    return render(request,'single_pages/kmpage.html', {'title': "kmpage"})

def gyPage(request):
    return render(request,'single_pages/gyPage.html', {'title': "gyPage"})

def blog(request):
    return render(request,'blog/templates/blog/index.html'), {'title': "blog"}

def todo(request):
    return render(request,'todo_app/templates/todo_app/index.html'), {'title': "todo"}

def gy(request):
    df = pd.read_csv("single_pages/static/single_pages/gydata.csv")
    post_list = [
        {"title": row["title"], "content": row["content"]}
        for _, row in df.iterrows()
    ]
    return render(request, 'single_pages/gyPage.html', {'title': 'gayeon Page', 'posts': post_list})

def km(request):
    df = pd.read_csv("single_pages/static/single_pages/kmdata.csv")
    post_list = df.to_dict(orient='records')
    return render(request, 'single_pages/kmpage.html', {'title': 'KyungMun', 'posts': post_list})

hw11_django/todo_app/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
)
from .models import ToDoList, ToDoItem

# Create your views here.
class ListListView(ListView):
    model = ToDoList
    template_name = 'todo_app/index.html'

class ItemListView(ListView):
    model = ToDoItem
    template_name = 'todo_app/todo_list.html'

    def get_queryset(self):
        return ToDoItem.objects.filter(todo_list_id=self.kwargs['list_id'])

    def get_context_data(self):
        context = super().get_context_data()
        context["todo_list"] = ToDoList.objects.get(id=self.kwargs['list_id'])
        return context

class ListCreate(CreateView):
    model = ToDoList
    fields = ["title"]

    def get_context_data(self):
        context = super(ListCreate, self).get_context_data()
        context["title"] = "Add a new list"
        return context

class ItemCreate(CreateView):
    model = ToDoItem
    fields = [
        "todo_list",
        "title",
        "description",
        "due_date",
    ]

    def get_initial(self):
        initial_data = super(ItemCreate, self).get_initial()
        todo_list = ToDoList.objects.get(id=self.kwargs["list_id"])
        initial_data["todo_list"] = todo_list
        return initial_data

    def get_context_data(self):
        context = super(ItemCreate, self).get_context_data()
        todo_list = ToDoList.objects.get(id=self.kwargs["list_id"])
        context["todo_list"] = todo_list
        context["title"] = "Create a new item"
        return context

    def get_success_url(self):
        return reverse("list", args=[self.object.todo_list_id])

class ItemUpdate(UpdateView):
    model = ToDoItem
    fields = [
        "todo_list",
        "title",
        "description",
        "due_date",
    ]

    def get_context_data(self):
        context = super(ItemUpdate, self).get_context_data()
        context["todo_list"] = self.object.todo_list
        context["title"] = "Edit item"
        return context

    def get_success_url(self):
        return reverse("list", args=[self.object.todo_list_id])

class ListDelete(DeleteView):
    model = ToDoList
    success_url = reverse_lazy("index")

class ItemDelete(DeleteView):
    model = ToDoItem

    def get_success_url(self):
        return reverse_lazy("list", args=[self.kwargs["list_id"]])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["todo_list"] = self.object.todo_list
        return context

hw11_django/single_pages/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    {%if title%}
    <title>{{title}}</title>
    {%else%}
    <title>2024-2 응용소프트웨어 7조</title>
    {%endif%}
    <link href="{% static 'single_pages/head.css' %}" rel="stylesheet" type="text/css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
    <div class="container-fluid">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" width="16" height="16">
            <path d="M575.8 255.5c0 18-15 32.1-32 32.1l-32 0 .7 160.2c0 2.7-.2 5.4-.5 8.1l0 16.2c0 22.1-17.9 40-40 40l-16 0c-1.1 0-2.2 0-3.3-.1c-1.4 .1-2.8 .1-4.2 .1L416 512l-24 0c-22.1 0-40-17.9-40-40l0-24 0-64c0-17.7-14.3-32-32-32l-64 0c-17.7 0-32 14.3-32 32l0 64 0 24c0 22.1-17.9 40-40 40l-24 0-31.9 0c-1.5 0-3-.1-4.5-.2c-1.2 .1-2.4 .2-3.6 .2l-16 0c-22.1 0-40-17.9-40-40l0-112c0-.9 0-1.9 .1-2.8l0-69.7-32 0c-18 0-32-14-32-32.1c0-9 3-17 10-24L266.4 8c7-7 15-8 22-8s15 2 21 7L564.8 231.5c8 7 12 15 11 24z"/></svg>
        <a class="navbar-brand" href="{% url 'single_pages:landing' %}">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'single_pages:gy' %}">Personal Page (Gayeon)</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'single_pages:km' %}">Personal Page (Kyungmun)</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'single_pages:blog' %}">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'single_pages:todo' %}">Todo</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<main role="main" class="container mt-4">
    {%block content%}{%endblock%}
</main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

hw11_django/single_pages/templates/single_pages/gyPage.html
{%extends 'layout.html'%}
{% load static %}

{%block content%}
<script type="text/javascript" src="{% static 'single_pages/send_message.js' %}"></script>

<br><br>
<h1>About me</h1>
<h3>우가연 / Gayeon Woo</h3>
<p><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-building-fill" viewBox="0 0 16 16">
    <path d="M3 0a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h3v-3.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 .5.5V16h3a1 1 0 0 0 1-1V1a1 1 0 0 0-1-1zm1 2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zm3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zm3.5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5M4 5.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zM7.5 5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5m2.5.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zM4.5 8h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5m2.5.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zm3.5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5"/>
  </svg>Jeonbuk National University</p>
<a class="btn btn-dark rounded-pill px-3" type="button" href="https://github.com/gayeonwoo">Github</a>
<br><br>
<h1>Contact</h1>
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16">
    <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414zM0 4.697v7.104l5.803-3.558zM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586zm3.436-.586L16 11.801V4.697z"/>
  </svg>
<p>202310082@jbnu.ac.kr</p>
<br><br>
<h1>Blog</h1>
{% if posts|length > 0 %}
{% for post in posts %}
        <h3>{{post.title}}</h3>
        <p>{{post.content}}</p>
        <hr>
{% endfor %}
{% else %}
        <p>아직 작성한 글이 없습니다.</p>
{% endif %}
<img src="{% static 'single_pages/images/star.jpg' %}" width="30%" align="right" onclick="message()">
{%endblock%}

hw11_django/single_pages/templates/single_pages/kmpage.html
{%extends 'layout.html'%}
{% load static %}
{% block title %}송경문 홈페이지{% endblock%}
{%block content%}
<br>
<div class="text-left">
    <h1 class="mb-3">송경문 / Song Kyung Mun</h1>
    <h2 class="mb-4">전북대학교 스마트팜학과 23학번</h2>
    <p class="lead">응용소프트웨어개발 홈페이지 만들기</p>
    <a href="https://github.com/SongKM2" target="_blank" class="btn btn-primary">Github</a>
    <hr>
    <img src="{% static 'single_pages/images/kmimage.jpg' %}" class="img-fluid rounded" alt="Profile Image" style="max-height: 200px;">
    <hr>
</div>
<div class="mt-5">
        <h2>Blog</h2>
{% if posts|length > 0 %}
        <div class="row">
            {% for post in posts %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">제목: {{ post.title }}</h5>
                            <p class="card-text">내용: {{ post.content }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p class="text-muted">아직 작성하지 않았습니다.</p>
    {% endif %}
</div>

<br>

<h1>Contact</h1>
<p>Email : songky040802@jbnu.ac.kr</p>

<a href="{% url 'single_pages:landing' %}" class="btn btn-secondary">첫 화면으로 가기</a>
{%endblock%}

hw11_django/single_pages/templates/single_pages/landing.html
{%extends 'layout.html'%}
{% load static %}

{%block content%}
<script type="text/javascript" src="{% static 'single_pages/kcal_dic.js' %}"></script>
<br><br>
    <h1>응용소프트웨어실습 7조</h1>
    <hr>
    <h2>칼로리 계산기</h2>
    <label for="food">섭취음식</label>
    <input type="text" id="food" value="바나나">
    <br><br>
    <label for="amount">섭취량(g)</label>
    <input type="text" id="amount" value="100">
    <br><br>
    <button type="submit" onclick="kcal()">계산</button>

    <p><span id="results"></span></p>

<script>


    function find_kcal(food,amount) {
        let total_kcal = 0
        if (food in kcal_dic) {
            total_kcal = parseFloat(kcal_dic[food]) / 100 * parseFloat(amount)
            return total_kcal
        } else {
            return -1
        }
    }

    function kcal(){
        let food=document.getElementById('food').value;
        let amount=document.getElementById('amount').value;
        let find=find_kcal(food,amount);
        if (find==-1) {
            document.getElementById("results").innerHTML =`${food}의 열량 정보가 없습니다`;
        } else {
            document.getElementById("results").innerHTML = `${food} ${amount}g : ${find}kcal`;
        }
        }
</script>
{%endblock%}